### ISSUE TITLE
(someday/maybe) Implement support for ed25519 algorithm

### ISSUE THREAD

**Issue by dmitrizagidulin** [anvilresearch/webcrypto#9]
Used by many secure messaging protocols, OSs, etc. See https://ianix.com/pub/ed25519-deployment.html

Doesn't appear to have WebCrypto API implementations in the browser.

References:

- [Ed25519: high-speed high-security signatures](https://ed25519.cr.yp.to/)
- https://en.wikipedia.org/wiki/EdDSA

Reference implementations:
- Sodium (and various Node bindings, like https://www.npmjs.com/package/tweetnacl etc).
- OpenSSH (and various Node bindings)
- https://www.npmjs.com/package/elliptic
- https://github.com/dazoe/ed25519 (native implementation for node)
- https://github.com/1p6/supercop.js
- https://stackoverflow.com/questions/19147619/what-implementions-of-ed25519-exist

**Comment by EternalDeiwos** [comment]
@dmitrizagidulin this is supported by indutny/elliptic and will (hopefully) be added to @trust/keyto soon.

See EternalDeiwos/keyto#1

**Comment by dmitrizagidulin** [comment]
@EternalDeiwos Awesome, thanks!

**Comment by christiansmith** [comment]
This is not a maybe, it's a definitely :)

**Comment by thelunararmy** [comment]
@EternalDeiwos @dmitrizagidulin Some further points to note:
1. Ed25519 is _supposedly_ supported in OpenSSL v1.1.x as [discussed by a contributor here](https://github.com/openssl/openssl/issues/309#issuecomment-216517132).
2. Further support for this work was [recently discussed on an OpenSSL blog post](https://www.openssl.org/blog/blog/2016/07/20/fips/)
3. The only holdup is when OpenSSL 1.1 will be supported by node. Since the current stables only support up to 1.0.2k. For reference:
```
node -pe process.versions       
```

So now the question is: Do we wait for node to support OpenSSL 1.1 or do we implement something from  indutny/elliptic etc?

**Comment by EternalDeiwos** [comment]
So, turns out the OpenSSL 1.1 does in fact have an implementation for Ed25519 (as of openssl/openssl#3503). The caveat to this is that they have yet to hook it up to the CLI.

My vote is that we use indutny/elliptic (seeing as we're using it already for EC) until OpenSSL sort themselves out.

Further discussion on the (still open) issue here: openssl/openssl#487

**Comment by thelunararmy** [comment]
Supported as of #54 using `elliptic`. Let us pray for node to support us in time.
